import { getProducts } from '@/actions/products-actions'
import Footer from '@/components/Footer/Footer'
import MenuTwo from '@/components/Header/Menu/MenuTwo'
import TopNavOne from '@/components/Header/TopNav/TopNavOne'
import Banner from '@/components/Home/Banner'
import Benefit from '@/components/Home/Benefit'
import Brand from '@/components/Home/Brand'
import Collection from '@/components/Home/Collection'
import Instagram from '@/components/Home/Instagram'
import TabFeatures from '@/components/Home/TabFeatures'
import WhatNewOne from '@/components/Home/WhatNewOne'
// import ModalNewsletter from '@/components/Modal/ModalNewsletter'
import SliderTwo from '@/components/Slider/SliderTwo'
import productData from '@/data/Product.json'
import { Product } from '@/types/product-type'
import React from 'react'



export const products: Product[] = [
  {
    id: 101,
    name: "Eco-Friendly Reusable Water Bottle",
    slug: "eco-water-bottle",
    permalink: "https://example.com/product/eco-water-bottle",
    date_created: "2024-01-15T10:00:00",
    date_created_gmt: "2024-01-15T04:00:00",
    date_modified: "2024-01-15T10:00:00",
    date_modified_gmt: "2024-01-15T04:00:00",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "Stay hydrated with our durable and stylish eco-friendly water bottle. Made from recycled materials and designed for daily use.",
    short_description: "Durable, eco-friendly water bottle.",
    sku: "WB-EF-001",
    price: "19.99",
    regular_price: "19.99",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    price_html: "<span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>19.99</bdi></span>",
    on_sale: true,
    purchasable: true,
    total_sales: 350,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 500,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: "0.3",
    dimensions: { length: "25", width: "8", height: "8" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "4.7",
    rating_count: 95,
    related_ids: [102, 103],
    upsell_ids: [104],
    cross_sell_ids: [105],
    parent_id: 0,
    categories: [{ id: 10, name: "Home Goods", slug: "home-goods" }, { id: 11, name: "Kitchen", slug: "kitchen" }],
    tags: [
      { id: 20, name: "eco-friendly", slug: "eco-friendly" },
      { id: 21, name: "reusable", slug: "reusable" },
      { id: 22, name: "water bottle", slug: "water-bottle" }
    ],
    images: [
      { id: 1001, date_created: "2024-01-15T09:50:00", date_created_gmt: "2024-01-15T03:50:00", date_modified: "2024-01-15T09:50:00", date_modified_gmt: "2024-01-15T03:50:00", src: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1708596763-OceanBottle_GO_Front_Forest-Green_2048px.jpg?crop=1xw:1.00xh;center,top&resize=980:*", name: "bottle-green.jpg", alt: "Green eco water bottle" }
    ],
    attributes: [
      { id: 1, name: "Color", position: 0, visible: true, variation: false, options: ["Green", "Blue", "Black"] }
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
    has_options: false
  },
  {
    id: 102,
    name: "Premium Wireless Headphones",
    slug: "premium-wireless-headphones",
    permalink: "https://example.com/product/premium-wireless-headphones",
    date_created: "2024-02-01T11:30:00",
    date_created_gmt: "2024-02-01T05:30:00",
    date_modified: "2024-06-20T14:00:00",
    date_modified_gmt: "2024-06-20T08:00:00",
    type: "variable",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "Immerse yourself in rich, high-fidelity sound with our premium wireless headphones. Featuring noise cancellation and long-lasting battery life.",
    short_description: "Superior audio experience, ultimate comfort.",
    sku: "HP-WL-002",
    price: "199.99",
    regular_price: "249.99",
    sale_price: "199.99",
    date_on_sale_from: "2025-06-20T00:00:00",
    date_on_sale_from_gmt: "2025-06-19T18:00:00",
    date_on_sale_to: "2025-07-31T23:59:59",
    date_on_sale_to_gmt: "2025-07-31T17:59:59",
    price_html: "<del><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>249.99</bdi></span></del> <ins><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>199.99</bdi></span></ins>",
    on_sale: true,
    purchasable: true,
    total_sales: 120,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false, // Managed by variations
    stock_quantity: null,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: "0.5",
    dimensions: { length: "20", width: "15", height: "10" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "electronics",
    shipping_class_id: 5,
    reviews_allowed: true,
    average_rating: "4.9",
    rating_count: 150,
    related_ids: [101, 106],
    upsell_ids: [107],
    cross_sell_ids: [],
    parent_id: 0,
    categories: [{ id: 12, name: "Electronics", slug: "electronics" }, { id: 13, name: "Audio", slug: "audio" }],
    tags: [{ id: 22, name: "headphones", slug: "headphones" }, { id: 23, name: "wireless", slug: "wireless" }],
    images: [
      { id: 2001, date_created: "2024-02-01T11:00:00", date_created_gmt: "2024-02-01T05:00:00", date_modified: "2024-02-01T11:00:00", date_modified_gmt: "2024-02-01T05:00:00", src: "https://5.imimg.com/data5/SELLER/Default/2022/5/GL/PT/GK/21711192/urbanista-miami-premium-wireless-headphones-anc-with-mic-upto-50-hours-playtime-ruby-red.jpg", name: "headphones-black.jpg", alt: "Black wireless headphones" },
      { id: 2002, date_created: "2024-02-01T11:05:00", date_created_gmt: "2024-02-01T05:05:00", date_modified: "2024-02-01T11:05:00", date_modified_gmt: "2024-02-01T05:05:00", src: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MUW43?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=YWtJWDJiK1RucFRzUlBFY0prZWhiQWtuVHYzMERCZURia3c5SzJFOTlPaXdubU0rbkxnaHhsbEhvaUZjM3lNU0hjZGNQNTM2dHV2dEwvczhmN3AzOXc", name: "headphones-silver.jpg", alt: "Silver wireless headphones" }
    ],
    attributes: [
      { id: 1, name: "Color", position: 0, visible: true, variation: true, options: ["Black", "Silver", "Rose Gold", "Olive", "Maroon"] },
      { id: 2, name: "Size", position: 1, visible: true, variation: true, options: ["S", "M", "L"] } // Example of another attribute
    ],
    default_attributes: [{ id: 1, name: "color", option: "Black" }],
    variations: [1021, 1022, 1023], // IDs of individual variations
    grouped_products: [],
    menu_order: 0,
    meta_data: [{ id: 3001, key: "_spec_feature_anc", value: "true" }],
    selectedAttributes: { "color": "Black" }, // Example: a specific variation is selected
    has_options: true
  },
  {
    id: 1021, // This is a variation of Product 102
    name: "Premium Wireless Headphones - Black",
    slug: "premium-wireless-headphones-black",
    permalink: "https://example.com/product/premium-wireless-headphones-black",
    date_created: "2024-02-01T11:40:00",
    date_created_gmt: "2024-02-01T05:40:00",
    date_modified: "2024-06-20T14:00:00",
    date_modified_gmt: "2024-06-20T08:00:00",
    type: "variation",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "", // Inherited from parent
    short_description: "", // Inherited from parent
    sku: "HP-WL-002-BLK",
    price: "199.99",
    regular_price: "249.99",
    sale_price: "199.99",
    date_on_sale_from: "2025-06-20T00:00:00",
    date_on_sale_from_gmt: "2025-06-19T18:00:00",
    date_on_sale_to: "2025-07-31T23:59:59",
    date_on_sale_to_gmt: "2025-07-31T17:59:59",
    price_html: "<del><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>249.99</bdi></span></del> <ins><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>199.99</bdi></span></ins>",
    on_sale: true,
    purchasable: true,
    total_sales: 70,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 150,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: "0.5",
    dimensions: { length: "20", width: "15", height: "10" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "electronics",
    shipping_class_id: 5,
    reviews_allowed: true,
    average_rating: "0.00", // Inherited from parent for display
    rating_count: 0, // Inherited from parent for display
    related_ids: [],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 102, // Link to parent product
    categories: [],
    tags: [],
    images: [
      { id: 2001, date_created: "2024-02-01T11:00:00", date_created_gmt: "2024-02-01T05:00:00", date_modified: "2024-02-01T11:00:00", date_modified_gmt: "2024-02-01T05:00:00", src: "https://gadgetstudiobd.com/wp-content/uploads/2022/03/EP-B52-SQUARE-1_1024x.jpg", name: "headphones-black.jpg", alt: "Black wireless headphones" }
    ],
    attributes: [
      { id: 1, name: "Color", options: ["Black", "Ash"] } // Specific attribute for this variation
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
    has_options: false
  },
  {
    id: 103,
    name: "Downloadable eBook: Mastering TypeScript",
    slug: "ebook-typescript",
    permalink: "https://example.com/product/ebook-typescript",
    date_created: "2024-03-01T09:00:00",
    date_created_gmt: "2024-03-01T03:00:00",
    date_modified: "2024-03-05T12:00:00",
    date_modified_gmt: "2024-03-05T06:00:00",
    type: "downloadable",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "Learn advanced TypeScript concepts and best practices with this comprehensive eBook. Includes code examples and practical exercises.",
    short_description: "Comprehensive guide to advanced TypeScript.",
    sku: "EB-TS-001",
    price: "29.99",
    regular_price: "29.99",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    price_html: "<span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>29.99</bdi></span>",
    on_sale: true,
    purchasable: true,
    total_sales: 50,
    virtual: true,
    downloadable: true,
    downloads: [
      { id: "file1", name: "Mastering TypeScript eBook", file: "https://example.com/downloads/mastering-typescript.pdf" },
      { id: "file2", name: "Code Examples.zip", file: "https://example.com/downloads/typescript-code-examples.zip" }
    ],
    download_limit: 5,
    download_expiry: 30, // days
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: "", // Virtual product, no weight
    dimensions: { length: "", width: "", height: "" }, // Virtual product, no dimensions
    shipping_required: false,
    shipping_taxable: false,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "4.8",
    rating_count: 25,
    related_ids: [],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    categories: [{ id: 14, name: "Books", slug: "books" }, { id: 15, name: "Programming", slug: "programming" }],
    tags: [{ id: 24, name: "typescript", slug: "typescript" }, { id: 25, name: "ebook", slug: "ebook" }],
    images: [
      { id: 3001, date_created: "2024-03-01T08:50:00", date_created_gmt: "2024-03-01T02:50:00", date_modified: "2024-03-01T08:50:00", date_modified_gmt: "2024-03-01T02:50:00", src: "https://example.com/images/ebook-typescript-cover.jpg", name: "ebook-typescript-cover.jpg", alt: "Mastering TypeScript eBook Cover" }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [{ id: 4001, key: "_file_format", value: "PDF, ZIP" }],
    has_options: false
  },
  {
    id: 104,
    name: "Stylish Leather Wallet",
    slug: "leather-wallet",
    permalink: "https://example.com/product/leather-wallet",
    date_created: "2024-04-10T15:00:00",
    date_created_gmt: "2024-04-10T09:00:00",
    date_modified: "2024-04-10T15:00:00",
    date_modified_gmt: "2024-04-10T09:00:00",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "Crafted from genuine leather, this wallet offers timeless style and practical organization for your cards and cash.",
    short_description: "Classic leather wallet.",
    sku: "ACC-LW-003",
    price: "45.00",
    regular_price: "45.00",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    price_html: "<span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>45.00</bdi></span>",
    on_sale: false,
    purchasable: true,
    total_sales: 80,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 120,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: "0.1",
    dimensions: { length: "12", width: "9", height: "1.5" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "4.6",
    rating_count: 40,
    related_ids: [101, 105],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    categories: [{ id: 16, name: "Accessories", slug: "accessories" }, { id: 17, name: "Wallets", slug: "wallets" }],
    tags: [{ id: 26, name: "leather", slug: "leather" }, { id: 27, name: "wallet", slug: "wallet" }],
    images: [
      { id: 4001, date_created: "2024-04-10T14:50:00", date_created_gmt: "2024-04-10T08:50:00", date_modified: "2024-04-10T14:50:00", date_modified_gmt: "2024-04-10T08:50:00", src: "https://example.com/images/wallet-brown.jpg", name: "wallet-brown.jpg", alt: "Brown leather wallet" }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
    has_options: false
  },
  {
    id: 105,
    name: "Digital Art Print: Abstract Sunset",
    slug: "digital-art-sunset",
    permalink: "https://example.com/product/digital-art-sunset",
    date_created: "2024-05-01T08:00:00",
    date_created_gmt: "2024-05-01T02:00:00",
    date_modified: "2024-05-01T08:00:00",
    date_modified_gmt: "2024-05-01T02:00:00",
    type: "virtual",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "Enhance your digital space with this vibrant abstract art print of a sunset. High-resolution file for personal use.",
    short_description: "Vibrant abstract sunset art print.",
    sku: "DIGI-ART-004",
    price: "15.00",
    regular_price: "15.00",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    price_html: "<span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>15.00</bdi></span>",
    on_sale: false,
    purchasable: true,
    total_sales: 60,
    virtual: true,
    downloadable: true,
    downloads: [
      { id: "artfile", name: "Abstract Sunset Print", file: "https://example.com/downloads/abstract-sunset.jpg" }
    ],
    download_limit: 3,
    download_expiry: -1,
    tax_status: "none", // Digital goods often non-taxable depending on region
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: false,
    shipping_taxable: false,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "4.9",
    rating_count: 30,
    related_ids: [],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    categories: [{ id: 18, name: "Digital Art", slug: "digital-art" }, { id: 19, name: "Home Decor", slug: "home-decor" }],
    tags: [{ id: 28, name: "abstract", slug: "abstract" }, { id: 29, name: "sunset", slug: "sunset" }],
    images: [
      { id: 5001, date_created: "2024-05-01T07:50:00", date_created_gmt: "2024-05-01T01:50:00", date_modified: "2024-05-01T07:50:00", date_modified_gmt: "2024-05-01T01:50:00", src: "https://example.com/images/abstract-sunset-preview.jpg", name: "abstract-sunset-preview.jpg", alt: "Preview of Abstract Sunset Digital Art" }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [{ id: 5002, key: "_resolution", value: "3000x2000px" }],
    has_options: false
  },
  {
    id: 106,
    name: "KitchenAid Stand Mixer",
    slug: "kitchenaid-mixer",
    permalink: "https://example.com/product/kitchenaid-mixer",
    date_created: "2024-06-10T10:00:00",
    date_created_gmt: "2024-06-10T04:00:00",
    date_modified: "2024-06-10T10:00:00",
    date_modified_gmt: "2024-06-10T04:00:00",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "The iconic KitchenAid Stand Mixer is an essential tool for any baker, offering power and versatility for all your culinary creations.",
    short_description: "Powerful and versatile stand mixer.",
    sku: "KITCH-MIX-005",
    price: "349.99",
    regular_price: "349.99",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    price_html: "<span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>349.99</bdi></span>",
    on_sale: false,
    purchasable: true,
    total_sales: 90,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 80,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: "10.0",
    dimensions: { length: "35", width: "25", height: "40" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "heavy-appliance",
    shipping_class_id: 15,
    reviews_allowed: true,
    average_rating: "4.9",
    rating_count: 200,
    related_ids: [101, 107],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    categories: [{ id: 11, name: "Kitchen", slug: "kitchen" }, { id: 20, name: "Appliances", slug: "appliances" }],
    tags: [{ id: 30, name: "baking", slug: "baking" }, { id: 31, name: "kitchenaid", slug: "kitchenaid" }],
    images: [
      { id: 6001, date_created: "2024-06-10T09:50:00", date_created_gmt: "2024-06-10T03:50:00", date_modified: "2024-06-10T09:50:00", date_modified_gmt: "2024-06-10T03:50:00", src: "https://example.com/images/kitchenaid-red.jpg", name: "kitchenaid-red.jpg", alt: "Red KitchenAid Stand Mixer" }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
    has_options: false
  },
  {
    id: 107,
    name: "Customizable Pet Collar",
    slug: "custom-pet-collar",
    permalink: "https://example.com/product/custom-pet-collar",
    date_created: "2024-06-20T14:30:00",
    date_created_gmt: "2024-06-20T08:30:00",
    date_modified: "2024-06-20T14:30:00",
    date_modified_gmt: "2024-06-20T08:30:00",
    type: "simple", // Could be variable if color/size are actual variations, but keeping simple for example
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "Design a unique collar for your beloved pet. Choose from various colors and add custom text for a personal touch.",
    short_description: "Personalized pet collar.",
    sku: "PET-COLLAR-006",
    price: "22.50",
    regular_price: "22.50",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    price_html: "<span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>22.50</bdi></span>",
    on_sale: false,
    purchasable: true,
    total_sales: 45,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 300,
    stock_status: "instock",
    backorders: "notify", // Allows backorders with notification
    backorders_allowed: true,
    backordered: false,
    sold_individually: false,
    weight: "0.05",
    dimensions: { length: "30", width: "2", height: "1" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "4.7",
    rating_count: 15,
    related_ids: [],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    categories: [{ id: 21, name: "Pet Supplies", slug: "pet-supplies" }],
    tags: [{ id: 32, name: "custom", slug: "custom" }, { id: 33, name: "pet", slug: "pet" }],
    images: [
      { id: 7001, date_created: "2024-06-20T14:20:00", date_created_gmt: "2024-06-20T08:20:00", date_modified: "2024-06-20T14:20:00", date_modified_gmt: "2024-06-20T08:20:00", src: "https://example.com/images/pet-collar-blue.jpg", name: "pet-collar-blue.jpg", alt: "Blue customizable pet collar" }
    ],
    attributes: [
      { id: 2, name: "Color", position: 0, visible: true, variation: false, options: ["Red", "Blue", "Green"] },
      { id: 3, name: "Size", position: 1, visible: true, variation: false, options: ["Small", "Medium", "Large"] },
      { id: 4, name: "Custom Text", position: 2, visible: true, variation: false, options: [] } // Example of a text input attribute
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
    has_options: true
  }
];
// Example of a product variation (these would typically be separate Product objects,
// but included here for context of how they relate to a variable product)
export const productVariations: Product[] = [
  {
    id: 103,
    name: "Premium Denim Jeans - Blue, Waist 32, Length 32",
    price: "75.00",
    regular_price: "90.00",
    sale_price: "75.00",
    featured: false,
    date_on_sale_from: "2025-06-01T00:00:00",
    date_on_sale_to: "2025-06-30T23:59:59",
    total_sales: 30,
    purchasable: true,
    stock_status: "instock",
    stock_quantity: 50,
    shipping_required: true,
    average_rating: "4.8",
    dimensions: { length: "40", width: "15", height: "2" },
    categories: [
      { id: 7, name: "Fashion", slug: "fashion" }
    ], // Categories typically on parent product
    images: [
      { id: 2001, date_created: "2024-02-01T11:00:00", date_created_gmt: "2024-02-01T05:00:00", date_modified: "2024-02-01T11:00:00", date_modified_gmt: "2024-02-01T05:00:00", src: "https://example.com/images/jeans-blue-front.jpg", alt: "Front view of blue denim jeans", name: "jeans-blue-front.jpg" },
      { id: 2001, date_created: "2024-02-01T11:00:00", date_created_gmt: "2024-02-01T05:00:00", date_modified: "2024-02-01T11:00:00", date_modified_gmt: "2024-02-01T05:00:00", src: "https://example.com/images/jeans-blue-front.jpg", alt: "Front view of blue denim jeans", name: "jeans-blue-front.jpg" }
    ],
    attributes: [
      { id: 3, name: "color", options: ["Blue"] },
      { id: 4, name: "waist", options: ["32"] },
      { id: 5, name: "length", options: ["32"] }
    ],
    default_attributes: [],
    description: "", // Description typically on parent product
    short_description: "", // Short description typically on parent product
    variations: [],
    type: "variation",
    status: "publish",
    catalog_visibility: "visible",
    on_sale: true,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: "0.8",
    shipping_taxable: true,
    shipping_class: "heavy-item",
    shipping_class_id: 10,
    reviews_allowed: true,
    rating_count: 0, // Rating usually on parent product
    price_html: "<del><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>90.00</bdi></span></del> <ins><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>75.00</bdi></span></ins>",
    has_options: false,
    slug: '',
    permalink: '',
    date_created: '',
    date_created_gmt: '',
    date_modified: '',
    date_modified_gmt: '',
    sku: '',
    date_on_sale_from_gmt: null,
    date_on_sale_to_gmt: null,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    tax_status: '',
    tax_class: '',
    related_ids: [],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    tags: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: []
  },
  // ... more variations would go here (e.g., Black, Waist 30, Length 30 etc.)
];



export default async function HomeTwo() {

  const { products } = await getProducts({});
  console.log(products.length);

  return (
    <>
      {/* <TopNavOne props="style-two bg-purple" slogan='Limited Offer: Free shipping on orders over $50' /> */}
      <div id="header" className='relative w-full'>
        <MenuTwo />
        <SliderTwo />
      </div>
      <Collection props="pt-5" />
      <WhatNewOne data={products} start={0} limit={8} />
      <Banner />
      <TabFeatures data={products} start={0} limit={8} />
      <Benefit props="md:mt-20 mt-10 py-10 px-2.5 bg-surface rounded-3xl" />
      {/* <Instagram /> */}
      <Brand />
      <Footer />
      {/* Black Friday Pop Up Modal */}
      {/* <ModalNewsletter /> */}
    </>
  )
}
