export const PATH = {
    HOME: '/',
    ABOUT: '/about',
    CONTACT: '/contact',
    SHOP: '/shop',
    PRODUCTS: '/products',
    CART: '/cart',
    CHECKOUT: '/checkout',
    THANKYOU: '/checkout/thank-you',
    ACCOUNT: '/account',
    LOGIN: '/login',
    REGISTER: '/register',
    ForgotPassword: '/forgot-password',
    DASHBOARD: '/dashboard',
    // PRODUCT_DETAIL: '/products/:id',
    // CATEGORIES: '/categories',
    // CATEGORY_DETAIL: '/categories/:id',
    // ORDERS: '/orders',
    // ORDER_DETAIL: '/orders/:id',
    WISHLIST: '/wishlist',
    // BLOG: '/blog',
    // BLOG_POST: '/blog/:id',
    PRIVACY_POLICY: '/privacy-policy',
    TERMS_CONDITIONS: '/terms-conditions'
} as const;
